# Generated by Django 3.2.9 on 2022-02-02 18:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='information',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this meeting', primary_key=True, serialize=False),
        ),
    ]
